name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Change working directory to amp-dev
      - name: Set working directory to amp-dev
        working-directory: amp-dev

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start the React app
      - name: Start React app
        run: npm start -- --silent

      # Wait for the app to start
      - name: Wait for app to start
        run: |
          while ! curl -s http://localhost:3000; do sleep 5; done

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --config video=false
